# .github/workflows/frontend-ci-cd.yml
name: Frontend CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm ci

      - name: 빌드
        run: npm run build

      - name: 빌드 결과 아티팩트로 저장
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./dist

  deploy:
    name: Deploy to macOS Server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./dist

      - name: 서버로 정적 파일 복사
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          target: "/Users/tolelom/Desktop/projects/tolelog"

      - name: Nginx 리로드 (프론트 반영)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            nginx -s reload
